### ISSUE TITLE
Add a "Try it online" page that makes use of liblouis-js 

### ISSUE THREAD

**Issue by bertfrees** [liblouis/liblouis.github.io#4]
More or less something like https://github.com/reiner-dolp/liblouis-web but with a different touch. It should always make use of the latest (snapshot) version of Liblouis.

**Comment by egli** [comment]
@bertfrees isn't this done?

**Comment by bertfrees** [comment]
Fixed by https://github.com/liblouis/liblouis.github.io/pull/7
